=== Pramodnagarajarao/DatabaseSystems-XMLDB/XML Database  - Code/company.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="company">
		<xs:annotation>
			<xs:documentation>This is my root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="department" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="division" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="employee" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="worksfor" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="deptId_primarykey">
			<xs:selector xpath="department"/>
			<xs:field xpath="deptId"/>
		</xs:key>
		<xs:key name="divId_primarykey">
			<xs:selector xpath="division"/>
			<xs:field xpath=" divId"/>
		</xs:key>
		<xs:key name="empId_primarykey">
			<xs:selector xpath="employee"/>
			<xs:field xpath=" empId"/>
		</xs:key>
		<xs:keyref name="housedDeptId_KeyRef" refer="deptId_primarykey">
			<xs:selector xpath="division"/>
			<xs:field xpath="housedDeptId"/>
		</xs:keyref>
		<xs:keyref name="managerEmpId_KeyRef" refer="empId_primarykey">
			<xs:selector xpath="division"/>
			<xs:field xpath="managerEmpId"/>
		</xs:keyref>
		<xs:key name="divId_empid_primarykey1">
			<xs:selector xpath="worksfor"/>
			<xs:field xpath="divId"/>
			<xs:field xpath="empId"/>
		</xs:key>
		<xs:keyref name="divId_KeyRef1" refer="divId_primarykey">
			<xs:selector xpath="worksfor"/>
			<xs:field xpath="divId"/>
		</xs:keyref>
		<xs:keyref name="empId_KeyRef1" refer="empId_primarykey">
			<xs:selector xpath="worksfor"/>
			<xs:field xpath="empId"/>
		</xs:keyref>
	</xs:element>
	<xs:element name="department">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="deptId">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="[A-Z][A-Z][A-Z]"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="deptName" type="xs:string"/>
				<xs:element name="deptAddr" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="division">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="divId" type="xs:string"/>
				<xs:element name="divName" type="xs:string"/>
				<xs:element name="divPhone">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="[1-9][0-9]{2}-[0-9]{3}-[0-9]{4}"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="housedDeptId" type="xs:string"/>
				<xs:element name="managerEmpId" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="employee">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="empId" type="xs:string"/>
				<xs:element name="empName" type="xs:string"/>
				<xs:element name="empPhone" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="[1-9][0-9]{2}-[0-9]{3}-[0-9]{4}"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="empOffice" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="worksfor">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="divId" type="xs:string"/>
				<xs:element name="empId" type="xs:string"/>
				<xs:element name="percentTime" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Pramodnagarajarao/DatabaseSystems-XMLDB/XML Database  - Code/company.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="file:///C:\Users\Pramod\Desktop\Nagarajarao_Pramod_HW3\Nagarajarao_Pramod_HW3/company.xsl"?>
<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:\Users\Pramod\Desktop\Nagarajarao_Pramod_HW3\Nagarajarao_Pramod_HW3/company.xsd" >
	<department>
		<deptId>ADM</deptId>
		<deptName>Admin</deptName>
		<deptAddr>LA</deptAddr>
	</department>
	<department>
		<deptId>FIN</deptId>
		<deptName>Finance</deptName>
		<deptAddr>LA</deptAddr>
	</department>
	<department>
		<deptId>SER</deptId>
		<deptName>Services</deptName>
		<deptAddr>LA</deptAddr>
	</department>
	<department>
		<deptId>OPR</deptId>
		<deptName>Operations</deptName>
		<deptAddr>LA</deptAddr>
	</department>
		<department>
		<deptId>BUS</deptId>
		<deptName>Business</deptName>
		<deptAddr>LA</deptAddr>
	</department>
	<division>
		<divId>div1</divId>
		<divName>HR</divName>
		<divPhone>346-232-3242</divPhone>
		<housedDeptId>ADM</housedDeptId>
		<managerEmpId>4</managerEmpId>
	</division>
		<division>
		<divId>div2</divId>
		<divName>Recruitment</divName>
		<divPhone>346-232-3243</divPhone>
		<housedDeptId>ADM</housedDeptId>
		<managerEmpId>1</managerEmpId>
	</division>
		<division>
		<divId>div3</divId>
		<divName>SysAd</divName>
		<divPhone>346-232-3244</divPhone>
		<housedDeptId>ADM</housedDeptId>
		<managerEmpId>3</managerEmpId>
	</division>
		<division>
		<divId>div4</divId>
		<divName>Payroll</divName>
		<divPhone>346-232-3245</divPhone>
		<housedDeptId>FIN</housedDeptId>
		<managerEmpId>5</managerEmpId>
	</division>
		<division>
		<divId>div5</divId>
		<divName>Accounting</divName>
		<divPhone>346-232-3246</divPhone>
		<housedDeptId>FIN</housedDeptId>
		<managerEmpId>5</managerEmpId>
	</division>
		<division>
		<divId>div6</divId>
		<divName>Networking</divName>
		<divPhone>346-232-3247</divPhone>
		<housedDeptId>SER</housedDeptId>
		<managerEmpId>2</managerEmpId>
	</division>
		<division>
		<divId>div7</divId>
		<divName>SaaS</divName>
		<divPhone>346-232-3248</divPhone>
		<housedDeptId>SER</housedDeptId>
		<managerEmpId>2</managerEmpId>
	</division>
		<division>
		<divId>div8</divId>
		<divName>Security</divName>
		<divPhone>346-232-3249</divPhone>
		<housedDeptId>SER</housedDeptId>
		<managerEmpId>1</managerEmpId>
	</division>
		<division>
		<divId>div9</divId>
		<divName>Convergence</divName>
		<divPhone>346-232-3250</divPhone>
		<housedDeptId>SER</housedDeptId>
		<managerEmpId>1</managerEmpId>
	</division>
		<division>
		<divId>div10</divId>
		<divName>Sales</divName>
		<divPhone>346-232-3251</divPhone>
		<housedDeptId>OPR</housedDeptId>
		<managerEmpId>1</managerEmpId>
	</division>
		<division>
		<divId>div11</divId>
		<divName>Marketing</divName>
		<divPhone>346-232-3252</divPhone>
		<housedDeptId>OPR</housedDeptId>
		<managerEmpId>4</managerEmpId>
	</division>
		<division>
		<divId>div12</divId>
		<divName>Engineering</divName>
		<divPhone>346-232-3253</divPhone>
		<housedDeptId>OPR</housedDeptId>
		<managerEmpId>4</managerEmpId>
	</division>
		<division>
		<divId>div13</divId>
		<divName>Business Developement</divName>
		<divPhone>346-232-3254</divPhone>
		<housedDeptId>BUS</housedDeptId>
		<managerEmpId>1</managerEmpId>
	</division>
		<division>
		<divId>div14</divId>
		<divName>Business Analysis</divName>
		<divPhone>346-232-3255</divPhone>
		<housedDeptId>BUS</housedDeptId>
		<managerEmpId>1</managerEmpId>
	</division>
	<employee>
		<empId>1</empId>
		<empName>PSmith</empName>
		<empPhone>243-235-3253</empPhone>
		<empOffice>LA</empOffice>
	</employee>
		<employee>
		<empId>2</empId>
		<empName>Wong</empName>
		<empPhone>224-234-9065</empPhone>
		<empOffice>LA</empOffice>
	</employee>
		<employee>
		<empId>3</empId>
		<empName>Jack</empName>
		<empPhone>243-235-4566</empPhone>
		<empOffice>LA</empOffice>
	</employee>
		<employee>
		<empId>4</empId>
		<empName>Anne</empName>
		<empPhone>324-876-3768</empPhone>
		<empOffice>LA</empOffice>
	</employee>
		<employee>
		<empId>5</empId>
		<empName>Ben</empName>
		<empPhone>453-249-3275</empPhone>
		<empOffice>LA</empOffice>
	</employee>
		<employee>
		<empId>6</empId>
		<empName>Monica</empName>
		<empPhone>935-487-3859</empPhone>
		<empOffice>LA</empOffice>
	</employee>
		<employee>
		<empId>7</empId>
		<empName>Jennifer</empName>
		<empPhone>935-487-3869</empPhone>
		<empOffice>LA</empOffice>
	</employee>
		<employee>
		<empId>8</empId>
		<empName>Mary</empName>
		<empPhone>932-487-3859</empPhone>
		<empOffice>LA</empOffice>
	</employee>
	<worksfor>
		<divId>div1</divId>
		<empId>4</empId>
		<percentTime>60</percentTime>
	</worksfor>
	<worksfor>
		<divId>div2</divId>
		<empId>4</empId>
		<percentTime>10</percentTime>
	</worksfor>
	<worksfor>
		<divId>div3</divId>
		<empId>4</empId>
		<percentTime>10</percentTime>
	</worksfor>
	<worksfor>
		<divId>div13</divId>
		<empId>4</empId>
		<percentTime>5</percentTime>
	</worksfor>
	<worksfor>
		<divId>div14</divId>
		<empId>4</empId>
		<percentTime>5</percentTime>
	</worksfor>
	<worksfor>
		<divId>div2</divId>
		<empId>5</empId>
		<percentTime>10</percentTime>
	</worksfor>
	<worksfor>
		<divId>div3</divId>
		<empId>5</empId>
		<percentTime>10</percentTime>
	</worksfor>
	<worksfor>
		<divId>div4</divId>
		<empId>5</empId>
		<percentTime>50</percentTime>
	</worksfor>
	<worksfor>
		<divId>div5</divId>
		<empId>5</empId>
		<percentTime>30</percentTime>
	</worksfor>
	<worksfor>
		<divId>div2</divId>
		<empId>3</empId>
		<percentTime>20</percentTime>
	</worksfor>
	<worksfor>
		<divId>div3</divId>
		<empId>3</empId>
		<percentTime>20</percentTime>
	</worksfor>
	<worksfor>
		<divId>div8</divId>
		<empId>3</empId>
		<percentTime>60</percentTime>
	</worksfor>
	<worksfor>
		<divId>div2</divId>
		<empId>6</empId>
		<percentTime>10</percentTime>
	</worksfor>
	<worksfor>
		<divId>div3</divId>
		<empId>6</empId>
		<percentTime>10</percentTime>
	</worksfor>
	<worksfor>
		<divId>div6</divId>
		<empId>6</empId>
		<percentTime>60</percentTime>
	</worksfor>
	<worksfor>
		<divId>div7</divId>
		<empId>6</empId>
		<percentTime>20</percentTime>
	</worksfor>
	<worksfor>
		<divId>div2</divId>
		<empId>1</empId>
		<percentTime>5</percentTime>
	</worksfor>
	<worksfor>
		<divId>div3</divId>
		<empId>1</empId>
		<percentTime>5</percentTime>
	</worksfor>
	<worksfor>
		<divId>div6</divId>
		<empId>1</empId>
		<percentTime>15</percentTime>
	</worksfor>
	<worksfor>
		<divId>div8</divId>
		<empId>1</empId>
		<percentTime>5</percentTime>
	</worksfor>
	<worksfor>
		<divId>div10</divId>
		<empId>1</empId>
		<percentTime>60</percentTime>
	</worksfor>
	<worksfor>
			<divId>div13</divId>
		<empId>1</empId>
		<percentTime>5</percentTime>
	</worksfor>
	<worksfor>
			<divId>div9</divId>
		<empId>1</empId>
		<percentTime>3</percentTime>
	</worksfor>
	<worksfor>
			<divId>div14</divId>
		<empId>1</empId>
		<percentTime>2</percentTime>
	</worksfor>
	<worksfor>
			<divId>div2</divId>
		<empId>2</empId>
		<percentTime>10</percentTime>
	</worksfor>
	<worksfor>
			<divId>div3</divId>
		<empId>2</empId>
		<percentTime>10</percentTime>
	</worksfor>
	<worksfor>
			<divId>div6</divId>
		<empId>2</empId>
		<percentTime>30</percentTime>
	</worksfor>
	<worksfor>
			<divId>div7</divId>
		<empId>2</empId>
		<percentTime>10</percentTime>
	</worksfor>
		<worksfor>
			<divId>div1</divId>
		<empId>2</empId>
		<percentTime>10</percentTime>
	</worksfor>
		<worksfor>
			<divId>div8</divId>
		<empId>2</empId>
		<percentTime>15</percentTime>
	</worksfor>
		<worksfor>
			<divId>div4</divId>
		<empId>2</empId>
		<percentTime>15</percentTime>
	</worksfor>
		<worksfor>
			<divId>div7</divId>
		<empId>7</empId>
		<percentTime>90</percentTime>
	</worksfor>
		<worksfor>
			<divId>div2</divId>
		<empId>7</empId>
		<percentTime>5</percentTime>
	</worksfor>
		<worksfor>
			<divId>div3</divId>
		<empId>7</empId>
		<percentTime>5</percentTime>
	</worksfor>
		<worksfor>
			<divId>div11</divId>
		<empId>8</empId>
		<percentTime>90</percentTime>
	</worksfor>
		<worksfor>
			<divId>div2</divId>
		<empId>8</empId>
		<percentTime>5</percentTime>
	</worksfor>
		<worksfor>
			<divId>div3</divId>
		<empId>8</empId>
		<percentTime>5</percentTime>
	</worksfor>
</company>
